# Generated by Django 6.0.1 on 2026-01-15 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinerecord',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
