# Generated by Django 6.0.1 on 2026-01-31 18:21

import ocean_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_data', '0002_marinerecord_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesGrowthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Detailed species info')),
                ('min_temp', models.FloatField(help_text='Min Temp (°C)')),
                ('max_temp', models.FloatField(help_text='Max Temp (°C)')),
                ('ideal_ph', models.FloatField(help_text='Ideal pH level')),
                ('salinity_ppt', models.FloatField(default=35.0, help_text='Salinity (ppt)')),
                ('oxygen_level', models.FloatField(default=6.0, help_text='Oxygen (mg/L)')),
            ],
        ),
        migrations.AlterField(
            model_name='marinerecord',
            name='location',
            field=models.CharField(max_length=100, validators=[ocean_data.models.validate_coastal_only]),
        ),
    ]
