# Generated by Django 6.0.1 on 2026-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_data', '0003_speciesgrowthcondition_alter_marinerecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinerecord',
            name='salinity',
            field=models.FloatField(default=35.0),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='ideal_ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='max_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='min_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='oxygen_level',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='speciesgrowthcondition',
            name='salinity_ppt',
            field=models.FloatField(default=35.0),
        ),
    ]
