# Generated by Django 6.0.1 on 2026-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_data', '0004_marinerecord_salinity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinerecord',
            name='latitude',
            field=models.FloatField(default=19.076),
        ),
        migrations.AddField(
            model_name='marinerecord',
            name='longitude',
            field=models.FloatField(default=72.8777),
        ),
    ]
